"""empty message

Revision ID: 4f4530b2eedb
Revises: ede6d9e7c139
Create Date: 2021-05-28 14:08:01.499854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f4530b2eedb'
down_revision = 'ede6d9e7c139'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('ft_attempts', sa.Integer(), nullable=True))
    op.add_column('player', sa.Column('tp_attempts', sa.Integer(), nullable=True))
    op.add_column('player', sa.Column('th_attempts', sa.Integer(), nullable=True))
    op.drop_column('player', 'tp_attemps')
    op.drop_column('player', 'ft_attemps')
    op.drop_column('player', 'th_attemps')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('th_attemps', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('player', sa.Column('ft_attemps', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('player', sa.Column('tp_attemps', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('player', 'th_attempts')
    op.drop_column('player', 'tp_attempts')
    op.drop_column('player', 'ft_attempts')
    # ### end Alembic commands ###
